In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
yeild_curve_data = pd.read_csv('yeild_curve_data - Sheet1 (1).csv')

In [3]:
yeild_curve_data

,Date,1 Mo,2 Mo,3 Mo,6 Mo,1 Yr,2 Yr,3 Yr,5 Yr,7 Yr,10 Yr,20 Yr,30 Yr
0,01/03/00,NaN,NaN,5.48,5.81,6.09,6.38,6.42,6.50,6.65,6.58,6.94,6.61
1,01/04/00,NaN,NaN,5.43,5.75,6.00,6.30,6.34,6.40,6.56,6.49,6.84,6.53
2,01/05/00,NaN,NaN,5.44,5.74,6.05,6.38,6.43,6.51,6.68,6.62,6.95,6.64
3,01/06/00,NaN,NaN,5.41,5.69,6.03,6.35,6.39,6.46,6.63,6.57,6.86,6.58
4,01/07/00,NaN,NaN,5.38,5.66,6.00,6.31,6.35,6.42,6.58,6.52,6.82,6.55
5,01/10/00,NaN,NaN,5.42,5.64,6.07,6.38,6.42,6.49,6.62,6.57,6.86,6.59
6,01/11/00,NaN,NaN,5.43,5.66,6.13,6.45,6.49,6.57,6.72,6.67,6.94,6.68
7,01/12/00,NaN,NaN,5.45,5.70,6.16,6.49,6.53,6.63,6.76,6.72,6.97,6.71
8,01/13/00,NaN,NaN,5.41,5.66,6.10,6.40,6.45,6.54,6.67,6.63,6.88,6.65
9,01/14/00,NaN,NaN,5.41,5.69,6.13,6.44,6.49,6.59,6.71,6.69,6.91,6.69
10,01/18/00,NaN,NaN,5.56,5.79,6.15,6.47,6.53,6.65,6.78,6.75,6.94,6.75
11,01/19/00,NaN,NaN,5.51,5.78,6.12,6.46,6.51,6.62,6.75,6.73,6.91,6.72
12,01/20/00,NaN,NaN,5.48,5.84,6.13,6.49,6.55,6.67,6.80,6.79,6.93,6.74
13,01/21/00,NaN,NaN,5.47,5.83,6.12,6.48,6.54,6.67,6.80,6.79,6.91,6.71
14,01/24/00,NaN,NaN,5.55,5.77,6.13,6.43,6.48,6.59,6.71,6.69,6.86,6.65
15,01/25/00,NaN,NaN,5.57,5.78,6.13,6.44,6.50,6.60,6.72,6.70,6.84,6.64
16,01/26/00,NaN,NaN,5.58,5.78,6.15,6.45,6.51,6.62,6.72,6.69,6.79,6.60
17,01/27/00,NaN,NaN,5.59,5.79,6.19,6.51,6.58,6.67,6.72,6.68,6.73,6.53
18,01/28/00,NaN,NaN,5.65,5.86,6.25,6.58,6.62,6.68,6.72,6.66,6.65,6.45
19,01/31/00,NaN,NaN,5.76,5.97,6.30,6.61,6.65,6.71,6.75,6.68,6.72,6.49
20,02/01/00,NaN,NaN,5.71,5.95,6.30,6.60,6.63,6.68,6.71,6.62,6.66,6.43
21,02/02/00,NaN,NaN,5.66,5.94,6.24,6.63,6.66,6.69,6.71,6.60,6.61,6.32
22,02/03/00,NaN,NaN,5.63,5.86,6.16,6.56,6.56,6.56,6.63,6.49,6.52,6.17
23,02/04/00,NaN,NaN,5.67,5.94,6.19,6.63,6.64,6.64,6.68,6.53,6.54,6.23
24,02/07/00,NaN,NaN,5.72,6.04,6.23,6.68,6.72,6.76,6.80,6.64,6.62,6.34
25,02/08/00,NaN,NaN,5.69,6.02,6.22,6.69,6.74,6.74,6.73,6.59,6.51,6.22
26,02/09/00,NaN,NaN,5.66,5.99,6.20,6.69,6.75,6.77,6.78,6.56,6.60,6.32
27,02/10/00,NaN,NaN,5.67,5.98,6.20,6.67,6.74,6.78,6.87,6.67,6.67,6.35
28,02/11/00,NaN,NaN,5.66,5.98,6.17,6.65,6.73,6.77,6.81,6.63,6.62,6.29
29,02/14/00,NaN,NaN,5.68,6.04,6.19,6.62,6.68,6.72,6.74,6.56,6.55,6.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5043,03/02/20,1.41,1.27,1.13,0.95,0.89,0.84,0.85,0.88,1.01,1.10,1.46,1.66
5044,03/03/20,1.11,1.05,0.95,0.83,0.73,0.71,0.72,0.77,0.91,1.02,1.44,1.64
5045,03/04/20,1.00,0.87,0.72,0.68,0.59,0.67,0.68,0.75,0.90,1.02,1.45,1.67
5046,03/05/20,0.92,0.83,0.62,0.53,0.48,0.59,0.61,0.67,0.81,0.92,1.34,1.56
5047,03/06/20,0.79,0.64,0.45,0.41,0.39,0.49,0.53,0.58,0.69,0.74,1.09,1.25
5048,03/09/20,0.57,0.52,0.33,0.27,0.31,0.38,0.40,0.46,0.56,0.54,0.87,0.99
5049,03/10/20,0.57,0.55,0.44,0.43,0.43,0.50,0.58,0.63,0.73,0.76,1.16,1.28
5050,03/11/20,0.42,0.42,0.42,0.40,0.40,0.50,0.58,0.66,0.78,0.82,1.13,1.30
5051,03/12/20,0.41,0.33,0.33,0.37,0.39,0.50,0.58,0.66,0.82,0.88,1.27,1.49
5052,03/13/20,0.33,0.30,0.28,0.38,0.38,0.49,0.58,0.70,0.89,0.94,1.31,1.56
5053,03/16/20,0.25,0.25,0.24,0.29,0.29,0.36,0.43,0.49,0.67,0.73,1.10,1.34
5054,03/17/20,0.12,0.18,0.19,0.24,0.30,0.47,0.54,0.66,0.91,1.02,1.45,1.63
5055,03/18/20,0.04,0.03,0.02,0.08,0.21,0.54,0.66,0.79,1.08,1.18,1.60,1.77
5056,03/19/20,0.04,0.04,0.04,0.06,0.20,0.44,0.53,0.66,1.00,1.12,1.56,1.78
5057,03/20/20,0.04,0.05,0.05,0.05,0.15,0.37,0.41,0.52,0.82,0.92,1.35,1.55
5058,03/23/20,0.01,0.04,0.02,0.08,0.17,0.28,0.31,0.38,0.63,0.76,1.12,1.33
5059,03/24/20,0.01,0.01,0.01,0.09,0.25,0.38,0.44,0.52,0.75,0.84,1.19,1.39
5060,03/25/20,0.00,0.00,0.00,0.07,0.19,0.34,0.41,0.56,0.77,0.88,1.23,1.45
5061,03/26/20,0.01,0.01,0.00,0.04,0.13,0.30,0.36,0.51,0.72,0.83,1.20,1.42
5062,03/27/20,0.01,0.03,0.03,0.02,0.11,0.25,0.30,0.41,0.60,0.72,1.09,1.29
5063,03/30/20,0.04,0.07,0.12,0.12,0.14,0.23,0.29,0.39,0.57,0.70,1.10,1.31
5064,03/31/20,0.05,0.12,0.11,0.15,0.17,0.23,0.29,0.37,0.55,0.70,1.15,1.35
5065,04/01/20,0.03,0.07,0.09,0.14,0.16,0.23,0.28,0.37,0.51,0.62,1.04,1.27
5066,04/02/20,0.09,0.10,0.09,0.15,0.14,0.23,0.29,0.39,0.53,0.63,1.04,1.26
5067,04/03/20,0.09,0.11,0.10,0.15,0.15,0.23,0.30,0.39,0.52,0.62,1.05,1.24
5068,04/06/20,0.09,0.13,0.15,0.17,0.20,0.27,0.35,0.44,0.58,0.67,1.08,1.27
5069,04/07/20,0.10,0.13,0.14,0.20,0.20,0.28,0.36,0.48,0.64,0.75,1.13,1.32
5070,04/08/20,0.14,0.17,0.22,0.24,0.23,0.27,0.34,0.47,0.65,0.77,1.18,1.37
5071,04/09/20,0.20,0.27,0.25,0.24,0.25,0.23,0.29,0.41,0.60,0.73,1.15,1.35
5072,04/13/20,0.17,0.29,0.26,0.27,0.27,0.25,0.31,0.44,0.63,0.76,1.19,1.39